"""Generate Liquibase 038 SQL seed for owner AEZ farmer registry (450 rows)."""
from __future__ import annotations

import json
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_TS = ROOT / "frontend" / "src" / "demo" / "aezFarmerRegistry.ts"
OUT_SQL = ROOT / "backend" / "src" / "main" / "resources" / "db" / "changelog" / "changes" / "038-aez-farmer-registry-seed.sql"
OUT_YAML = ROOT / "backend" / "src" / "main" / "resources" / "db" / "changelog" / "changes" / "038-aez-farmer-registry-seed.yaml"

NS = uuid.UUID("03803803-8038-4038-8038-038038038038")


def load_rows() -> list[dict]:
    text = REGISTRY_TS.read_text(encoding="utf-8")
    marker = "export const AEZ_FARMER_REGISTRY"
    idx = text.index(marker)
    start = text.index("= [", idx) + 2
    end = text.rindex("]") + 1
    return json.loads(text[start:end])


def district_code(name: str) -> str:
    return name.strip().upper().replace(" ", "_")


def esc(value: str) -> str:
    return value.replace("'", "''")


def farmer_uuid(fid: int) -> str:
    return f"a0380000-0000-4000-8000-{fid:012d}"


def farm_uuid(fid: int) -> str:
    return f"b0380000-0000-4000-8000-{fid:012d}"


def sector_uuid(district: str, sector: str) -> str:
    return str(uuid.uuid5(NS, f"sector:{district_code(district)}:{sector.strip().upper()}"))


def cell_uuid(district: str, sector: str, cell: str) -> str:
    return str(
        uuid.uuid5(NS, f"cell:{district_code(district)}:{sector.strip().upper()}:{cell.strip().upper()}")
    )


def main() -> None:
    rows = load_rows()
    assert len(rows) == 450

    sectors: dict[tuple[str, str], tuple[str, str, str]] = {}
    cells: dict[tuple[str, str, str], tuple[str, str, str, str]] = {}
    for row in rows:
        d, s, c = row["district"], row["sector"], row["cell"]
        sectors[(d, s)] = (sector_uuid(d, s), district_code(d), s)
        cells[(d, s, c)] = (cell_uuid(d, s, c), sector_uuid(d, s), c, s)

    parts: list[str] = [
        "-- 038 Owner AEZ farmer registry seed (idempotent).",
        "-- Generated by scripts/generate_aez_liquibase.py — do not hand-edit.",
        "",
        "-- 1) Sectors (by district name → districts.code)",
    ]

    for sid, dcode, sname in sorted(sectors.values(), key=lambda x: (x[1], x[2])):
        scode = sname.strip().upper().replace(" ", "_")[:32]
        parts.append(
            f"""INSERT INTO sectors (id, district_id, code, name, created_at, updated_at, version, status, deleted)
SELECT '{sid}'::uuid, d.id, '{esc(scode)}', '{esc(sname)}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ACTIVE', FALSE
FROM districts d
WHERE d.code = '{esc(dcode)}' AND d.deleted = false
  AND NOT EXISTS (
    SELECT 1 FROM sectors s WHERE s.district_id = d.id AND s.code = '{esc(scode)}' AND s.deleted = false
  );"""
        )

    parts.append("")
    parts.append("-- 2) Cells")
    for cid, sid, cname, sname in sorted(cells.values(), key=lambda x: (x[3], x[2])):
        ccode = cname.strip().upper().replace(" ", "_")[:32]
        parts.append(
            f"""INSERT INTO cells (id, sector_id, code, name, created_at, updated_at, version, status, deleted)
SELECT '{cid}'::uuid, '{sid}'::uuid, '{esc(ccode)}', '{esc(cname)}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ACTIVE', FALSE
WHERE EXISTS (SELECT 1 FROM sectors s WHERE s.id = '{sid}'::uuid AND s.deleted = false)
  AND NOT EXISTS (
    SELECT 1 FROM cells c WHERE c.sector_id = '{sid}'::uuid AND c.code = '{esc(ccode)}' AND c.deleted = false
  );"""
        )

    parts.append("")
    parts.append("-- 3) Farmers")
    for row in rows:
        n = int(row["farmerId"].split("-")[1])
        fid = farmer_uuid(n)
        nid = f"NID{row['farmerId'].replace('-', '')}"
        phone = row["phoneNumber"].replace(" ", "")
        dcode = district_code(row["district"])
        sid = sector_uuid(row["district"], row["sector"])
        cid = cell_uuid(row["district"], row["sector"], row["cell"])
        parts.append(
            f"""INSERT INTO farmers (
  id, first_name, last_name, farmer_code, national_id, phone_number,
  district_id, sector_id, cell_id,
  created_at, updated_at, version, status, deleted
)
SELECT
  '{fid}'::uuid, '{esc(row["firstName"])}', '{esc(row["lastName"])}', '{esc(row["farmerId"])}', '{esc(nid)}', '{esc(phone)}',
  d.id, '{sid}'::uuid, '{cid}'::uuid,
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ACTIVE', FALSE
FROM districts d
WHERE d.code = '{esc(dcode)}' AND d.deleted = false
  AND NOT EXISTS (SELECT 1 FROM farmers f WHERE f.farmer_code = '{esc(row["farmerId"])}' AND f.deleted = false);"""
        )

    parts.append("")
    parts.append("-- 4) Farms (one per farmer)")
    for row in rows:
        n = int(row["farmerId"].split("-")[1])
        fid = farmer_uuid(n)
        fmid = farm_uuid(n)
        farm_code = f"FARM-{row['farmerId']}"
        farm_name = f"{row['farmerName']} — {row['crop']}"
        dcode = district_code(row["district"])
        sid = sector_uuid(row["district"], row["sector"])
        cid = cell_uuid(row["district"], row["sector"], row["cell"])
        size = row["fieldSizeHa"]
        crop = row["crop"]
        parts.append(
            f"""INSERT INTO farms (
  id, farmer_id, farm_code, farm_name, farm_size_ha, crop_type,
  district_id, sector_id, cell_id,
  created_at, updated_at, version, status, deleted
)
SELECT
  '{fmid}'::uuid, '{fid}'::uuid, '{esc(farm_code)}', '{esc(farm_name)}', {size}, '{esc(crop)}',
  d.id, '{sid}'::uuid, '{cid}'::uuid,
  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 'ACTIVE', FALSE
FROM districts d
WHERE d.code = '{esc(dcode)}' AND d.deleted = false
  AND EXISTS (SELECT 1 FROM farmers fr WHERE fr.id = '{fid}'::uuid AND fr.deleted = false)
  AND NOT EXISTS (SELECT 1 FROM farms fm WHERE fm.farm_code = '{esc(farm_code)}' AND fm.deleted = false);"""
        )

    OUT_SQL.write_text("\n".join(parts) + "\n", encoding="utf-8")
    OUT_YAML.write_text(
        """databaseChangeLog:
  - changeSet:
      id: 038-aez-farmer-registry-seed
      author: aegisterra
      comment: >
        Owner agroecological farmer registry (AGT-0001..AGT-0450) with district → AEZ
        placement, sector/cell admin units, and one farm per farmer. Idempotent by farmer_code / farm_code.
      changes:
        - sqlFile:
            path: db/changelog/changes/038-aez-farmer-registry-seed.sql
            splitStatements: true
            stripComments: true
            endDelimiter: ;
""",
        encoding="utf-8",
    )
    print(f"wrote {OUT_SQL} ({OUT_SQL.stat().st_size} bytes)")
    print(f"wrote {OUT_YAML}")
    print(f"sectors={len(sectors)} cells={len(cells)} farmers={len(rows)}")


if __name__ == "__main__":
    main()
